name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Load Google Services File
        env:
          DATA: ${{ secrets.HA1_GOOGLE_SERVICES_JSON_BASE64 }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and sign APK with Gradle
        run: ./gradlew assembleRelease
        env:
          HA1_KEYSTORE_PASSWORD: ${{ secrets.HA1_KEYSTORE_PASSWORD }}
          HA1_GITHUB_TOKEN: ${{ secrets.HA1_GITHUB_TOKEN }}
          HA1_VERSION_SOURCE: 'ci'

      - name: Upload APK Zip
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ github.sha }}
          path: app/build/outputs/apk/release/Han1meViewer-v*.apk
